// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using StellarGear.Infrastructure.Persistence;

#nullable disable

namespace StellarGear.Infrastructure.Migrations
{
    [DbContext(typeof(StellarGearContext))]
    [Migration("20260527203751_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StellarGear.Domain.Entities.AlertaEmergencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_alerta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_alerta");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdLeitura")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_leitura");

                    b.Property<int>("IdMedico")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_medico");

                    b.Property<string>("NivelGravidade")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("nivel_gravidade");

                    b.Property<string>("Resolvido")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("resolvido");

                    b.HasKey("Id");

                    b.HasIndex("IdLeitura");

                    b.HasIndex("IdMedico");

                    b.ToTable("alerta_emergencia", (string)null);
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.HistoricoMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_historico");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_registro");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("diagnostico");

                    b.Property<int>("IdPassageiro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_passageiro");

                    b.HasKey("Id");

                    b.HasIndex("IdPassageiro");

                    b.ToTable("historico_medico", (string)null);
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.LeituraSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_leitura");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Batimentos")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("batimentos");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_leitura");

                    b.Property<decimal?>("Humidade")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("humidade");

                    b.Property<int>("IdTraje")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_traje");

                    b.Property<decimal?>("Temperatura")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("temperatura");

                    b.HasKey("Id");

                    b.HasIndex("IdTraje");

                    b.ToTable("leitura_sensor", (string)null);
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_medico");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Crm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("crm");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("especialidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("medico", (string)null);
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.Passageiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_passageiro");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("Idade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("StatusMedico")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("status_medico");

                    b.HasKey("Id");

                    b.ToTable("passageiro", (string)null);
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.Traje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_traje");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoRfid")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("codigo_rfid");

                    b.Property<DateTime?>("DataAlocacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_alocacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdPassageiro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_passageiro");

                    b.HasKey("Id");

                    b.HasIndex("IdPassageiro");

                    b.ToTable("traje", (string)null);
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.AlertaEmergencia", b =>
                {
                    b.HasOne("StellarGear.Domain.Entities.LeituraSensor", "Leitura")
                        .WithMany("Alertas")
                        .HasForeignKey("IdLeitura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StellarGear.Domain.Entities.Medico", "Medico")
                        .WithMany("Alertas")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leitura");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.HistoricoMedico", b =>
                {
                    b.HasOne("StellarGear.Domain.Entities.Passageiro", "Passageiro")
                        .WithMany("Historicos")
                        .HasForeignKey("IdPassageiro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passageiro");
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.LeituraSensor", b =>
                {
                    b.HasOne("StellarGear.Domain.Entities.Traje", "Traje")
                        .WithMany("Leituras")
                        .HasForeignKey("IdTraje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Traje");
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.Traje", b =>
                {
                    b.HasOne("StellarGear.Domain.Entities.Passageiro", "Passageiro")
                        .WithMany("Trajes")
                        .HasForeignKey("IdPassageiro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passageiro");
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.LeituraSensor", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.Medico", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.Passageiro", b =>
                {
                    b.Navigation("Historicos");

                    b.Navigation("Trajes");
                });

            modelBuilder.Entity("StellarGear.Domain.Entities.Traje", b =>
                {
                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
